name: 'L2TP/IPSec VPN'
description: 'Connect to L2TP/IPSec VPN'
author: 'Kiyoshi Mizumoto'
branding:
  icon: 'log-in'
  color: 'blue'
inputs:
  server:
    description: >
      the IP address or host name of the server
    required: true
  username:
    description: >
      the username you are to use
    required: true
  password:
    description: >
      the password you are to use. If you don't specify a password, pptpsetup will ask for one.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
